#!/bin/bash

# Source: https://github.com/snapcrafters/arduino/blob/master/scripts/check-permissions

GROUP=$(stat -c '%G' /dev/ttyS0)

YAD_TITLE="Grant permissions"
TEXT1="\
<b>WARNING\\n\\n\
The Tauno Serial Plotter will not be able to read serial data from boards</b> because this user (<tt>$USER</tt>) does not have permission to access USB boards. To fix this, please open a terminal and run the following command.\\n\
"
COMMAND="\
<tt>sudo usermod -a -G $GROUP $USER</tt>\
"
TEXT2="\
\\n\
After this, <b>reboot your computer</b> and start the Tauno Serial Plotter again.\
"
TEXT4="\\n\\n"

if [[ -n "$DEBUG_CHECK_PERMISSIONS" ||  ( ! -f $SNAP_USER_COMMON/dont-warn-permissions && "$(groups)" != *"$GROUP"* ) ]]; then
    # I'm using `form` here instead of `text`, because that allows me to split
    # the text into multiple parts which can each be selected independently.
    yad \
    --title="$YAD_TITLE" \
    --form \
    --center \
    --width=600 \
    --field="$TEXT1":LBL \
    --field="$COMMAND":LBL \
    --field="$TEXT2":LBL \
    --field="$TEXT4":LBL \
    --field="Don't show this warning again":CHK \
    --focus-field=2 \
    --on-top \
    --borders=50 \
    --selectable-labels \
    --button=gtk-ok 2>&1 | grep TRUE && touch $SNAP_USER_COMMON/dont-warn-permissions
fi

exec "$@"