name: tauno-serial-plotter
base: core22
version: '1.19.3'
summary: Simple serial plotter
description: |
  Tauno Serial Plotter is simple serial plotter for Arduino and others.

  If no ports show up. Then:

  `sudo usermod -a -G dialout $USER`

  `sudo snap connect tauno-serial-plotter:raw-usb`

grade: stable         # 'devel', must be 'stable' to release into candidate/stable channels
confinement: strict   # strict # 'devmode' or 'strict' to release into candidate/stable channels
compression: lzo      # improves startup time for large snaps

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  tauno-serial-plotter:
    source: .
    plugin: python
    build-packages:
      - python3
    python-packages:
      - pyserial
      - pyqtgraph
      - PyQt5
    stage-packages:
      - python3
      - python3-pyqt5
      - libqt5gui5
    after: [desktop-qt5]
  
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      #- ttf-ubuntu-font-family
      - libxkbcommon0
      - fonts-ubuntu
      - fonts-dejavu-core
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - libqt5widgets5
      - libqt5x11extras5
      - libqt5dbus5
      - libxkbcommon0
      - libqt5core5a
      - libxcb-xinput0
      - libglib2.0-0
      - libegl1
      - libegl1-mesa
      - libxcb1
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-sync1
      #- try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
      #- qtwayland5
      

  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av src/tauno-serial-plotter.py $SNAPCRAFT_PART_INSTALL/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/
      cp -f src/icons/tauno-plotter.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/tauno-plotter.svg

  # copy icons to snap
  desktop-gui:
    plugin: dump
    source: src/icons/
    organize:
      '*.svg' : bin/icons/
    stage:
      - bin/icons/

  #scripts:
  #  plugin: dump
  #  source: scripts # dir
  #  stage-packages:
  #    - yad

# https://github.com/snapcrafters/arduino/blob/master/snapcraft.yaml
apps:
  tauno-serial-plotter:
    command: bin/desktop-launch tauno-serial-plotter.py
    #command-chain:
    # Give execution permission to this file!
    #   - setup.sh
    environment:
      QT_QPA_PLATFORM: xcb  # Force the use of X11 platform
      QT_DEBUG_PLUGINS: 1  # Optional: This helps debug Qt plugin issues
      PYTHONPATH: $SNAP/usr/lib/python3:$SNAP/usr/lib/python3/site-packages:$PYTHONPATH
      # Fallback to XWayland if running in a Wayland session.
      # DISABLE_WAYLAND: 1
    plugs:
      #- unity7
      - home
      - removable-media
      - network
      - serial-port
      - raw-usb
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - network-bind
      - hardware-observe
