name: tauno-serial-plotter
base: core18 
version: '1.19.3'
summary: Simple serial plotter
description: |
  Tauno Serial Plotter is simple serial plotter for Arduino and others.

  If no ports show up. Then:

  `sudo usermod -a -G dialout $USER`

  `sudo snap connect tauno-serial-plotter:raw-usb`

grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64

parts:
  tauno-serial-plotter:
    source: .
    plugin: python
    requirements: ['requirements.txt']
    stage-packages:
      - python3-pyqt5
      - qtwayland5
    after: [desktop-qt5]
  
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
    
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av src/tauno-serial-plotter.py $SNAPCRAFT_PART_INSTALL/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/
      cp -f src/icons/tauno-plotter.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/tauno-plotter.svg

  # copy icons to snap
  desktop-gui:
    plugin: dump
    source: src/icons/
    organize:
      '*.svg' : bin/icons/
    stage:
      - bin/icons/


# https://github.com/snapcrafters/arduino/blob/master/snapcraft.yaml
apps:
  tauno-serial-plotter:
    command: bin/desktop-launch tauno-serial-plotter.py
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
    - unity7
    - home
    - removable-media
    - network
    - serial-port
    - raw-usb
    - desktop
    - desktop-legacy
    - x11
    - wayland
    - opengl
    - network-bind
    - hardware-observe
