name: tauno-serial-plotter # you probably want to 'snapcraft register <name>'
base: core18 
version: '1.14'
summary: Simple serial plotter # 79 char long summary
description: |
  Tauno-Serial-Plotter is simple serial plotter for Arduino and others.

grade: stable #stable # 'devel', must be 'stable' to release into candidate/stable channels
confinement: strict # strict # 'devmode' or 'strict' to release into candidate/stable channels
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64

parts:
  tauno-serial-plotter:
    source: .
    plugin: python
    requirements: ['requirements.txt']
    stage-packages:
      - python3-pyqt5
    after: [desktop-qt5]
  
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
    
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av src/tauno-serial-plotter.py $SNAPCRAFT_PART_INSTALL/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/
      cp -f src/icons/tauno-plotter.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/tauno-plotter.svg
  # copy icons to snap
  desktop-gui:
    plugin: dump
    source: ./src/icons/
    organize:
      '*.svg' : bin/icons/
    stage:
      - bin/icons/

apps:
  tauno-serial-plotter:
    command: bin/desktop-launch tauno-serial-plotter.py
    # https://github.com/snapcrafters/arduino/blob/master/snapcraft.yaml
    #command-chain:
    #  - check-permissions
    plugs: 
    - desktop
    - desktop-legacy
    - x11
    - unity7
    - wayland
    - opengl
    - network
    - network-bind
    - serial-port
    #- removable-media # ?
    - raw-usb
