name: tauno-serial-plotter
title: Tauno Serial Plotter
base: core24
grade: stable
confinement: strict
version: '1.20.4'
summary: Simple serial plotter
description: |
  Tauno Serial Plotter is simple serial plotter for Arduino and others.

  Note: For serial port access, run:
  sudo usermod -a -G dialout $USER
  sudo snap connect tauno-serial-plotter:raw-usb
  sudo snap connect tauno-serial-plotter:serial-port
compression: lzo
license: GNU General Public License v3.0 
contact: sedumacre@gmail.com

platforms:
  amd64:
  arm64:

slots:
  qt6-content:
    interface: content
    content: qt6
    default-provider: qt6-core24
    target: $SNAP/qt6

apps:
  tauno-serial-plotter:
    extensions: [ gnome ]
    command: bin/tauno-serial-plotter.py
    command-chain: [ bin/snap-command-wrapper ]
    common-id: tauno-serial-plotter.desktop
    plugs:
    - home
    - removable-media
    - network
    - serial-port
    - raw-usb
    - desktop
    - desktop-legacy
    - x11
    - wayland
    - opengl
    - network-bind
    - hardware-observe

  

parts:
  tauno-serial-plotter:
    source: .
    plugin: python
    python-requirements: ['requirements.txt']
    stage-packages:
      - python3-pyqt6
      - qt6-wayland
    override-build: |
      craftctl default
      # Ensure the script is in the bin folder and executable
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -av src/tauno-serial-plotter.py $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/tauno-serial-plotter.py
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/
      cp -f src/icons/tauno-plotter.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/tauno-plotter.svg

  desktop-wrapper:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/bin/snap-command-wrapper
      #!/bin/sh
      export XDG_DATA_DIRS=\$SNAP/qt6/usr/share:\$XDG_DATA_DIRS
      export QT_PLUGIN_PATH=\$SNAP/qt6/usr/lib/\$CRAFT_ARCH_TRIPLET/qt6/plugins
      export QML2_IMPORT_PATH=\$SNAP/qt6/usr/lib/\$CRAFT_ARCH_TRIPLET/qt6/qml
      export QTCHOICE_PLATFORM_PLUGIN_PATH=\$SNAP/qt6/usr/lib/\$CRAFT_ARCH_TRIPLET/qt6/plugins/platforms
      exec "\$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/snap-command-wrapper

  # copy icons to snap
  desktop-gui:
    plugin: dump
    source: src/icons/
    organize:
      '*.svg' : bin/icons/
    stage:
      - bin/icons/
